export type TCardAppearance = {
	fontName?: string
	fontSize?: 'XXS' | 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'XXXL'
	// shortcuts from colorSchemaName
	color?: string
	textColor?: string
	colorSchemaName?: string
}

export type TCardboxStat = {
	created_at: Date
	changed_at: Date
}

export type TCardSide = {
	header?: string
	text: string
	footer?: string
	appearance? : TCardAppearance
}

export type TCard = {
	id: string
	ownDesign?: boolean
	sides?: Array<TCardSide>
};

export type TCardEnriched = TCard & { cardboxSides?: Array<TCardboxSide> };

export type TPreparedSide = { id?: string } & TCardSide & TCardboxSide;
export type TPreparedCard = Array<TPreparedSide>; // [{id, text, color, font...}, {id, text, color, font...}]...
export type TPreparedCards = Array<TPreparedCard>; // [ [id...], [id...] ]

export type TCardboxSide = { name: string } & TCardAppearance;

export type TCardbox = {
	id?: string
	title?: string
	isLocal?: boolean
	author?: string
	stat?: TCardboxStat
	sides?: Array<TCardboxSide> // 2, TBD
	cards?: Array<TCard>
}

/*
create table
public.cardboxes (
	id bigint generated by default as identity,
	created_at timestamp with time zone not null default now(),
	changed_at timestamp with time zone null default now(),
	owner uuid null default auth.uid (),
	title character varying null default ''::character varying,
	description text null default ''::text,
	public boolean null default false,
	version integer null default 1,
	side1title character varying null default ''::character varying,
	side2title character varying null default ''::character varying,
	side1schema character varying null default ''::character varying,
	side2schema character varying null default ''::character varying,
	"side1fontSize" character varying null default ''::character varying,
	"side2fontSize" character varying null default ''::character varying,
	"side1fontName" character varying null default ''::character varying,
	"side2fontName" character varying null default ''::character varying,
	author character varying null default ''::character varying,
	constraint cardboxes_pkey primary key (id)
) tablespace pg_default;
 */

export type TSCardbox = {
	id: number
	created_at: Date
	changed_at: Date
	owner: string

	title: string
	author: string
	description: string

	public: boolean
	version: number

	side1title: string
	side2title: string

	side1schema: string
	side2schema: string

	side1fontSize: 'XXS' | 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'XXXL'
	side2fontSize: 'XXS' | 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'XXXL'

	side1fontName: string
	side2fontName: string

	cardsCount?: number
}

export type TSCardboxKey = keyof TSCardbox;
