import {TFontSize} from "../types-common.ts";

/*
create table
public.cardboxes (
	id bigint generated by default as identity,
	created_at timestamp with time zone not null default now(),
	changed_at timestamp with time zone null default now(),
	owner uuid null default auth.uid (),
	title character varying null default ''::character varying,
	description text null default ''::text,
	public boolean null default false,
	version integer null default 1,
	side1title character varying null default ''::character varying,
	side2title character varying null default ''::character varying,
	side1schema character varying null default ''::character varying,
	side2schema character varying null default ''::character varying,
	"side1fontSize" character varying null default ''::character varying,
	"side2fontSize" character varying null default ''::character varying,
	"side1fontName" character varying null default ''::character varying,
	"side2fontName" character varying null default ''::character varying,
	author character varying null default ''::character varying,
	constraint cardboxes_pkey primary key (id)
) tablespace pg_default;
 */

export type TSCardbox = {
	id: number
	created_at: Date
	changed_at: Date
	owner: string

	title: string
	author: string
	description: string

	public: boolean
	version: number

	side1title: string
	side2title: string

	side1schema: string
	side2schema: string

	side1fontSize: TFontSize
	side2fontSize: TFontSize

	side1fontName: string
	side2fontName: string

	cards_count: number
	unstable?: boolean
}

export type TSCardboxKey = keyof TSCardbox;
