// https://gwfh.mranftl.com/fonts/oswald?subsets=cyrillic-ext,latin,latin-ext
export const Fonts: Record<string, string> = {
	// Roboto: 'https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxM.woff',
	'Roboto *': '/roboflex.woff',
	'Roboto Slab *': '/roboto-slab.woff',
	'Advent Pro *': '/advent-pro.woff',
	'Amatic *': '/amatic-sc.woff',
	'Bad Script *': '/bad-script.woff',
	'Bona Nova *': '/bona-nova.woff',
	'Comfortaa *': '/comfortaa.woff',
	'Cormorant *': '/cormorant.woff',
	'Oswald *': '/oswald.woff',
	'Philosopher *': '/philosopher.woff',
	'PT Sans *': '/pt-sans.woff',
	// 'Noto Sans': 'https://fonts.gstatic.com/s/notosans/v7/o-0IIpQlx3QUlC5A4PNr5TRG.woff',
	Cookie: 'https://fonts.gstatic.com/s/cookie/v8/syky-y18lb0tSbf9kgqU.woff',
	// Quicksand: 'https://fonts.gstatic.com/s/quicksand/v7/6xKtdSZaM9iE8KbpRA_hK1QL.woff',
	// Trirong: 'https://fonts.gstatic.com/s/trirong/v3/7r3GqXNgp8wxdOdOn4so3g.woff',
	// Trocchi: 'https://fonts.gstatic.com/s/trocchi/v6/qWcqB6WkuIDxDZLcPrxeuw.woff',
	'Henny Penny': 'https://fonts.gstatic.com/s/hennypenny/v5/wXKvE3UZookzsxz_kjGSfPQtvXQ.woff',
	Orbitron: 'https://fonts.gstatic.com/s/orbitron/v9/yMJRMIlzdpvBhQQL_Qq7dys.woff',
	Sacramento: 'https://fonts.gstatic.com/s/sacramento/v5/buEzpo6gcdjy0EiZMBUG4C0f-w.woff',
	'Snowburst One': 'https://fonts.gstatic.com/s/snowburstone/v5/MQpS-WezKdujBsXY3B7I-UT7SZieOA.woff',
	// Syncopate: 'https://fonts.gstatic.com/s/syncopate/v9/pe0sMIuPIYBCpEV5eFdCBfe5.woff',
	Wallpoet: 'https://fonts.gstatic.com/s/wallpoet/v9/f0X10em2_8RnXVVdUObp58I.woff',
	// 'Sirin Stencil': 'https://fonts.gstatic.com/s/sirinstencil/v6/mem4YaWwznmLx-lzGfN7MdRyRc9MAQ.woff',
};
