/*
create table
  public.cards (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    changed_at timestamp with time zone null,
    box_id bigint not null,
    side1header character varying null,
    side1text character varying null,
    side1footer character varying null,
    side2header character varying null,
    side2text character varying null,
    side2footer character varying null,
    "hasOwnDesign" boolean null,
    side1schema character varying null,
    "side1fontSize" character varying null,
    "side1fontName" character varying null,
    side2schema character varying null,
    "side2fontSize" character varying null,
    "side2fontName" character varying null,
    constraint cards_pkey primary key (id)
  ) tablespace pg_default;
*/

import {TFontSize} from "../types-common.ts";

export type TSCard = {
	id: number
	created_at: Date
	changed_at: Date
	box_id: number

	side1header: string
	side1text: string
	side1footer: string

	side2header: string
	side2text: string
	side2footer: string

	hasOwnDesign: boolean

	side1schema: string
	side2schema: string

	side1fontSize: TFontSize
	side2fontSize: TFontSize

	side1fontName: string
	side2fontName: string
}

export type TSCardKey = keyof TSCard;
